type TranslationMap = Record<string, string>;

const en: TranslationMap = {
  // Card UI
  'card.no_alerts': 'No active alerts.',
  'card.sensor_unavailable': 'Alert sensor is {state}.',
  'card.preview': 'Sample Data',
  'card.read_details': 'Read Details',
  'card.open_source': 'Open {provider} Source',
  'card.zones_count': '{count} zones',
  'card.zone_count_singular': '{count} zone',
  'card.dismiss': 'Dismiss',
  'card.dismissed_toast': 'Dismissed: {event}',
  'card.dismissed_toast_undo': 'Undo',

  // Detail labels
  'detail.issued': 'Issued',
  'detail.onset': 'Onset',
  'detail.expires': 'Expires',
  'detail.area': 'Area',
  'detail.source': 'Source',
  'detail.description': 'Description',
  'detail.instructions': 'Instructions',

  // Progress bar
  'progress.start': 'Start',
  'progress.now': 'Now',
  'progress.end': 'End',
  'progress.ongoing': 'Ongoing',
  'progress.expires_in_label': 'Expires in',
  'progress.starts_in_label': 'Starts in',
  'progress.tbd': 'TBD',
  'progress.na': 'N/A',
  'progress.expired_label': 'Expired',
  'progress.compact_active': 'for {time}',
  'progress.compact_prep': 'in {time}',
  'progress.compact_ongoing': 'ongoing',
  'progress.compact_expired': 'expired {time} ago',

  // Relative time
  'time.just_now': 'just now',
  'time.in_less_than_1m': 'in <1m',
  'time.minutes_ago': '{m}m ago',
  'time.in_minutes': 'in {m}m',
  'time.hours_ago': '{dur} ago',
  'time.in_hours': 'in {dur}',
  'time.days_ago': '{d}d ago',
  'time.in_days': 'in {d}d',

  // Badge labels
  'badge.severity_extreme': 'Extreme',
  'badge.severity_severe': 'Severe',
  'badge.severity_moderate': 'Moderate',
  'badge.severity_minor': 'Minor',
  'badge.severity_unknown': 'Unknown',
  'badge.certainty_observed': 'Observed',
  'badge.certainty_likely': 'Likely',
  'badge.certainty_possible': 'Possible',
  'badge.certainty_unlikely': 'Unlikely',
  'badge.certainty_unknown': 'Unknown',

  // Editor
  'editor.entities': 'Entities',
  'editor.title': 'Title (optional)',
  'editor.provider': 'Alert provider',
  'editor.provider_auto': 'Auto-detect',
  'editor.provider_nws': 'NWS (United States)',
  'editor.provider_bom': 'BoM (Australia)',
  'editor.provider_meteoalarm': 'MeteoAlarm (Europe)',
  'editor.provider_pirateweather': 'PirateWeather',
  'editor.provider_dwd': 'DWD (Germany)',
  'editor.provider_meteoswiss': 'MeteoSwiss (Switzerland)',
  'editor.provider_eccc': 'ECCC (Canada)',
  'editor.provider_cap': 'CAP Alerts (multi-region)',
  'editor.device': 'CAP Alerts device (optional)',
  'editor.device_helper': 'Pulls in every active alert sensor under this device automatically.',
  'editor.zones': 'Zones (optional)',
  'editor.zones_helper': 'Comma-separated BoM area_id codes, e.g. NSW_FL049',
  'editor.event_codes': 'Event codes (optional)',
  'editor.event_codes_helper': 'Comma-separated event codes, e.g. TOW, SVW (NWS) or 31, 95 (DWD)',
  'editor.exclude_event_codes': 'Exclude event codes (optional)',
  'editor.exclude_event_codes_helper': 'Comma-separated event codes to exclude, e.g. SCY (NWS) or 22 (DWD)',
  'editor.sort_order': 'Sort order',
  'editor.sort_default': 'Default',
  'editor.sort_onset': 'Onset time',
  'editor.sort_severity': 'Severity',
  'editor.color_theme': 'Color theme',
  'editor.color_severity': 'Severity-based',
  'editor.color_nws': 'NWS Official',
  'editor.color_meteoalarm': 'MeteoAlarm Awareness',
  'editor.color_eccc': 'ECCC Public Alerts',
  'editor.timezone': 'Timezone',
  'editor.tz_server': 'Server (Home Assistant)',
  'editor.tz_browser': 'Browser (local device)',
  'editor.min_severity': 'Minimum severity',
  'editor.severity_all': 'All severities',
  'editor.severity_minor': 'Minor or higher',
  'editor.severity_moderate': 'Moderate or higher',
  'editor.severity_severe': 'Severe or higher',
  'editor.severity_extreme': 'Extreme only',
  'editor.animations': 'Enable animations',
  'editor.enhance_contrast': 'Enhance contrast',
  'editor.enhance_contrast_off': 'Off',
  'editor.enhance_contrast_subtle': 'Subtle (default)',
  'editor.enhance_contrast_strict': 'Strict (WCAG AA)',
  'editor.deduplicate': 'Deduplicate alerts',
  'editor.deduplicate_headlines': 'Deduplicate headlines',
  'editor.show_details': 'Show detail panel',
  'editor.expand_details': 'Always expand details',
  'editor.show_metadata': 'Show metadata',
  'editor.show_description': 'Show description',
  'editor.show_instructions': 'Show instructions',
  'editor.show_geometry': 'Show area map',
  'editor.geometry_style': 'Area map style',
  'editor.geometry_style_shape': 'Outline only',
  'editor.geometry_style_map': 'Map tiles (online)',
  'editor.show_provider': 'Show provider label',
  'editor.show_source_link': 'Show source link',
  'editor.reformat_text': 'Reflow alert text (strip hard line breaks)',
  'editor.compact': 'Compact layout',
  'editor.font_size': 'Font size',
  'editor.font_size_small': 'Small',
  'editor.font_size_default': 'Default',
  'editor.font_size_large': 'Large',
  'editor.font_size_x_large': 'Extra large',
  'editor.hide_expired': 'Hide expired alerts',
  'editor.hide_no_alerts': 'Hide card when there are no active alerts',
  'editor.unavailable_behavior': 'When alert sensor is broken',
  'editor.unavailable_message': 'Show full notice',
  'editor.unavailable_compact': 'Show compact notice',
  'editor.unavailable_hide': 'Hide card (not recommended)',
  'editor.unavailable_hide_warning': 'Hiding the card when a sensor is unavailable can mask a broken alert source — an unavailable sensor is not proof of safety.',
  'editor.allow_dismiss': 'Allow dismissing alerts',
  'editor.show_dismiss_undo': 'Show undo notification on dismiss',
  'editor.dismissed_count': 'Dismissed: {count} alerts.',
  'editor.dismissed_count_singular': 'Dismissed: {count} alert.',
  'editor.restore_all': 'Restore all',
  'editor.show_preview': 'Show sample data',
  'editor.preview_hint': 'Preview card layout with sample alerts',
  'editor.preview_nudge': 'No active alerts — enable to preview the card layout.',
  'editor.entity_warning': 'Selected entity does not appear to contain weather alert data.',
  'editor.no_entities_hint': 'No supported weather alert entities found. A provider integration (e.g. NWS Alerts) must be installed first.',
  'editor.no_entities_hint_link': 'Supported providers',
  'editor.no_device_alerts_hint': 'No active alert sensors found under this device yet. The card will populate automatically when CAP Alerts publishes alerts.',

  // Editor section labels
  'editor.section_entity': 'Entities & Provider',
  'editor.section_filtering': 'Filtering',
  'editor.section_appearance': 'Appearance',
  'editor.section_detail_panel': 'Detail Panel',
  'editor.section_behavior': 'Behavior',
  'editor.section_dismissal': 'Dismissal',
  'editor.dismiss_trigger': 'Dismiss trigger',
  'editor.dismiss_trigger_button': 'Button only',
  'editor.dismiss_trigger_swipe': 'Swipe only',
  'editor.dismiss_trigger_both': 'Button and swipe',
  'editor.dismiss_button_style': 'Button style',
  'editor.dismiss_button_style_icon': 'Icon only',
  'editor.dismiss_button_style_labeled': 'Icon and label',
};

const fr: TranslationMap = {
  // Card UI
  'card.no_alerts': 'Aucune alerte active.',
  'card.sensor_unavailable': 'Le capteur d\'alerte est {state}.',
  'card.preview': 'Donnees d\'exemple',
  'card.read_details': 'Lire les details',
  'card.open_source': 'Ouvrir la source {provider}',
  'card.zones_count': '{count} zones',
  'card.zone_count_singular': '{count} zone',
  'card.dismiss': 'Ignorer',
  'card.dismissed_toast': 'Ignorée : {event}',
  'card.dismissed_toast_undo': 'Annuler',

  // Detail labels
  'detail.issued': 'Emis',
  'detail.onset': 'Debut',
  'detail.expires': 'Expire',
  'detail.area': 'Zone',
  'detail.source': 'Source',
  'detail.description': 'Description',
  'detail.instructions': 'Instructions',

  // Progress bar
  'progress.start': 'Debut',
  'progress.now': 'Maint.',
  'progress.end': 'Fin',
  'progress.ongoing': 'En cours',
  'progress.expires_in_label': 'Expire dans',
  'progress.starts_in_label': 'Commence dans',
  'progress.tbd': 'Ind.',
  'progress.na': 'N/D',
  'progress.expired_label': 'Expiré',
  'progress.compact_active': 'pour {time}',
  'progress.compact_prep': 'dans {time}',
  'progress.compact_ongoing': 'en cours',
  'progress.compact_expired': 'expiré il y a {time}',

  // Relative time
  'time.just_now': 'a l\'instant',
  'time.in_less_than_1m': 'dans <1m',
  'time.minutes_ago': 'il y a {m}m',
  'time.in_minutes': 'dans {m}m',
  'time.hours_ago': 'il y a {dur}',
  'time.in_hours': 'dans {dur}',
  'time.days_ago': 'il y a {d}j',
  'time.in_days': 'dans {d}j',

  // Badge labels
  'badge.severity_extreme': 'Extrême',
  'badge.severity_severe': 'Grave',
  'badge.severity_moderate': 'Modérée',
  'badge.severity_minor': 'Mineure',
  'badge.severity_unknown': 'Inconnue',
  'badge.certainty_observed': 'Observée',
  'badge.certainty_likely': 'Probable',
  'badge.certainty_possible': 'Possible',
  'badge.certainty_unlikely': 'Improbable',
  'badge.certainty_unknown': 'Inconnue',

  // Editor
  'editor.entities': 'Entites',
  'editor.title': 'Titre (optionnel)',
  'editor.provider': 'Fournisseur d\'alertes',
  'editor.provider_auto': 'Detection auto',
  'editor.provider_nws': 'NWS (Etats-Unis)',
  'editor.provider_bom': 'BoM (Australie)',
  'editor.provider_meteoalarm': 'MeteoAlarm (Europe)',
  'editor.provider_pirateweather': 'PirateWeather',
  'editor.provider_dwd': 'DWD (Allemagne)',
  'editor.provider_meteoswiss': 'MeteoSwiss (Suisse)',
  'editor.provider_eccc': 'ECCC (Canada)',
  'editor.provider_cap': 'Alertes CAP (multi-region)',
  'editor.device': 'Appareil CAP Alerts (optionnel)',
  'editor.device_helper': 'Recupere automatiquement chaque capteur d\'alerte actif sous cet appareil.',
  'editor.zones': 'Zones (optionnel)',
  'editor.zones_helper': 'Codes area_id BoM separes par des virgules, ex. NSW_FL049',
  'editor.event_codes': 'Codes d\'evenement (optionnel)',
  'editor.event_codes_helper': 'Codes d\'evenement separes par des virgules, ex. TOW, SVW (NWS) ou 31, 95 (DWD)',
  'editor.exclude_event_codes': 'Exclure codes d\'evenement (optionnel)',
  'editor.exclude_event_codes_helper': 'Codes d\'evenement a exclure, ex. SCY (NWS) ou 22 (DWD)',
  'editor.sort_order': 'Ordre de tri',
  'editor.sort_default': 'Par defaut',
  'editor.sort_onset': 'Heure de debut',
  'editor.sort_severity': 'Gravite',
  'editor.color_theme': 'Theme de couleur',
  'editor.color_severity': 'Base sur la gravite',
  'editor.color_nws': 'NWS officiel',
  'editor.color_meteoalarm': 'MeteoAlarm Vigilance',
  'editor.color_eccc': 'Alertes publiques ECCC',
  'editor.timezone': 'Fuseau horaire',
  'editor.tz_server': 'Serveur (Home Assistant)',
  'editor.tz_browser': 'Navigateur (appareil local)',
  'editor.min_severity': 'Gravite minimale',
  'editor.severity_all': 'Toutes les gravites',
  'editor.severity_minor': 'Mineure ou plus',
  'editor.severity_moderate': 'Moderee ou plus',
  'editor.severity_severe': 'Grave ou plus',
  'editor.severity_extreme': 'Extreme uniquement',
  'editor.animations': 'Activer les animations',
  'editor.enhance_contrast': 'Améliorer le contraste',
  'editor.enhance_contrast_off': 'Désactivé',
  'editor.enhance_contrast_subtle': 'Subtil (par défaut)',
  'editor.enhance_contrast_strict': 'Strict (WCAG AA)',
  'editor.deduplicate': 'Dedupliquer les alertes',
  'editor.deduplicate_headlines': 'Dédupliquer les titres',
  'editor.show_details': 'Afficher le panneau de details',
  'editor.expand_details': 'Toujours afficher les details',
  'editor.show_metadata': 'Afficher les metadonnees',
  'editor.show_description': 'Afficher la description',
  'editor.show_instructions': 'Afficher les instructions',
  'editor.show_geometry': 'Afficher la carte de zone',
  'editor.geometry_style': 'Style de la carte de zone',
  'editor.geometry_style_shape': 'Contour uniquement',
  'editor.geometry_style_map': 'Tuiles cartographiques (en ligne)',
  'editor.show_provider': 'Afficher le fournisseur',
  'editor.show_source_link': 'Afficher le lien source',
  'editor.reformat_text': 'Reformater le texte (supprimer les retours a la ligne)',
  'editor.compact': 'Disposition compacte',
  'editor.font_size': 'Taille de police',
  'editor.font_size_small': 'Petit',
  'editor.font_size_default': 'Par défaut',
  'editor.font_size_large': 'Grand',
  'editor.font_size_x_large': 'Très grand',
  'editor.hide_expired': 'Masquer les alertes expirées',
  'editor.hide_no_alerts': 'Masquer la carte sans alertes',
  'editor.unavailable_behavior': "Quand le capteur d'alerte est défaillant",
  'editor.unavailable_message': "Afficher l'avis complet",
  'editor.unavailable_compact': "Afficher l'avis compact",
  'editor.unavailable_hide': 'Masquer la carte (déconseillé)',
  'editor.unavailable_hide_warning': "Masquer la carte lorsqu'un capteur est indisponible peut dissimuler une source d'alerte défaillante — un capteur indisponible n'est pas une preuve de sécurité.",
  'editor.allow_dismiss': 'Permettre d\'ignorer les alertes',
  'editor.show_dismiss_undo': 'Afficher une notification d\'annulation',
  'editor.dismissed_count': 'Ignorées : {count} alertes.',
  'editor.dismissed_count_singular': 'Ignorée : {count} alerte.',
  'editor.restore_all': 'Tout restaurer',
  'editor.show_preview': 'Afficher les donnees exemples',
  'editor.preview_hint': 'Apercu de la disposition avec des alertes fictives',
  'editor.preview_nudge': 'Aucune alerte active — activez pour previsualiser la disposition.',
  'editor.entity_warning': 'L\'entite selectionnee ne semble pas contenir de donnees d\'alerte meteo.',
  'editor.no_entities_hint': 'Aucune entite d\'alerte meteo compatible trouvee. Une integration (ex. NWS Alerts) doit etre installee.',
  'editor.no_entities_hint_link': 'Fournisseurs supportes',
  'editor.no_device_alerts_hint': 'Aucun capteur d\'alerte actif trouve sous cet appareil pour le moment. La carte se remplira automatiquement lorsque CAP Alerts publiera des alertes.',

  // Editor section labels
  'editor.section_entity': 'Entite et fournisseur',
  'editor.section_filtering': 'Filtrage',
  'editor.section_appearance': 'Apparence',
  'editor.section_detail_panel': 'Panneau de details',
  'editor.section_behavior': 'Comportement',
  'editor.section_dismissal': 'Masquage',
  'editor.dismiss_trigger': 'Declencheur',
  'editor.dismiss_trigger_button': 'Bouton uniquement',
  'editor.dismiss_trigger_swipe': 'Glissement uniquement',
  'editor.dismiss_trigger_both': 'Bouton et glissement',
  'editor.dismiss_button_style': 'Style du bouton',
  'editor.dismiss_button_style_icon': 'Icone uniquement',
  'editor.dismiss_button_style_labeled': 'Icone et texte',
};

const es: TranslationMap = {
  // Card UI
  'card.no_alerts': 'Sin alertas activas.',
  'card.sensor_unavailable': 'El sensor de alertas esta {state}.',
  'card.preview': 'Datos de ejemplo',
  'card.read_details': 'Leer detalles',
  'card.open_source': 'Abrir fuente {provider}',
  'card.zones_count': '{count} zonas',
  'card.zone_count_singular': '{count} zona',
  'card.dismiss': 'Descartar',
  'card.dismissed_toast': 'Descartada: {event}',
  'card.dismissed_toast_undo': 'Deshacer',

  // Detail labels
  'detail.issued': 'Emitido',
  'detail.onset': 'Inicio',
  'detail.expires': 'Expira',
  'detail.area': 'Area',
  'detail.source': 'Fuente',
  'detail.description': 'Descripcion',
  'detail.instructions': 'Instrucciones',

  // Progress bar
  'progress.start': 'Inicio',
  'progress.now': 'Ahora',
  'progress.end': 'Fin',
  'progress.ongoing': 'En curso',
  'progress.expires_in_label': 'Expira en',
  'progress.starts_in_label': 'Comienza en',
  'progress.tbd': 'Pend.',
  'progress.na': 'N/D',
  'progress.expired_label': 'Expirada',
  'progress.compact_active': 'por {time}',
  'progress.compact_prep': 'en {time}',
  'progress.compact_ongoing': 'en curso',
  'progress.compact_expired': 'expiró hace {time}',

  // Relative time
  'time.just_now': 'ahora mismo',
  'time.in_less_than_1m': 'en <1m',
  'time.minutes_ago': 'hace {m}m',
  'time.in_minutes': 'en {m}m',
  'time.hours_ago': 'hace {dur}',
  'time.in_hours': 'en {dur}',
  'time.days_ago': 'hace {d}d',
  'time.in_days': 'en {d}d',

  // Badge labels
  'badge.severity_extreme': 'Extrema',
  'badge.severity_severe': 'Grave',
  'badge.severity_moderate': 'Moderada',
  'badge.severity_minor': 'Menor',
  'badge.severity_unknown': 'Desconocida',
  'badge.certainty_observed': 'Observada',
  'badge.certainty_likely': 'Probable',
  'badge.certainty_possible': 'Posible',
  'badge.certainty_unlikely': 'Improbable',
  'badge.certainty_unknown': 'Desconocida',

  // Editor
  'editor.entities': 'Entidades',
  'editor.title': 'Titulo (opcional)',
  'editor.provider': 'Proveedor de alertas',
  'editor.provider_auto': 'Deteccion auto',
  'editor.provider_nws': 'NWS (Estados Unidos)',
  'editor.provider_bom': 'BoM (Australia)',
  'editor.provider_meteoalarm': 'MeteoAlarm (Europa)',
  'editor.provider_pirateweather': 'PirateWeather',
  'editor.provider_dwd': 'DWD (Alemania)',
  'editor.provider_meteoswiss': 'MeteoSwiss (Suiza)',
  'editor.provider_eccc': 'ECCC (Canadá)',
  'editor.provider_cap': 'Alertas CAP (multi-region)',
  'editor.device': 'Dispositivo CAP Alerts (opcional)',
  'editor.device_helper': 'Incorpora automaticamente cada sensor de alerta activo bajo este dispositivo.',
  'editor.zones': 'Zonas (opcional)',
  'editor.zones_helper': 'Codigos area_id de BoM separados por comas, ej. NSW_FL049',
  'editor.event_codes': 'Codigos de evento (opcional)',
  'editor.event_codes_helper': 'Codigos de evento separados por comas, ej. TOW, SVW (NWS) o 31, 95 (DWD)',
  'editor.exclude_event_codes': 'Excluir codigos de evento (opcional)',
  'editor.exclude_event_codes_helper': 'Codigos de evento a excluir, ej. SCY (NWS) o 22 (DWD)',
  'editor.sort_order': 'Orden',
  'editor.sort_default': 'Predeterminado',
  'editor.sort_onset': 'Hora de inicio',
  'editor.sort_severity': 'Gravedad',
  'editor.color_theme': 'Tema de color',
  'editor.color_severity': 'Basado en gravedad',
  'editor.color_nws': 'NWS oficial',
  'editor.color_meteoalarm': 'MeteoAlarm Conciencia',
  'editor.color_eccc': 'Alertas públicas ECCC',
  'editor.timezone': 'Zona horaria',
  'editor.tz_server': 'Servidor (Home Assistant)',
  'editor.tz_browser': 'Navegador (dispositivo local)',
  'editor.min_severity': 'Gravedad minima',
  'editor.severity_all': 'Todas las gravedades',
  'editor.severity_minor': 'Menor o superior',
  'editor.severity_moderate': 'Moderada o superior',
  'editor.severity_severe': 'Grave o superior',
  'editor.severity_extreme': 'Solo extrema',
  'editor.animations': 'Activar animaciones',
  'editor.enhance_contrast': 'Mejorar contraste',
  'editor.enhance_contrast_off': 'Desactivado',
  'editor.enhance_contrast_subtle': 'Sutil (por defecto)',
  'editor.enhance_contrast_strict': 'Estricto (WCAG AA)',
  'editor.deduplicate': 'Deduplicar alertas',
  'editor.deduplicate_headlines': 'Deduplicar titulares',
  'editor.show_details': 'Mostrar panel de detalles',
  'editor.expand_details': 'Siempre expandir detalles',
  'editor.show_metadata': 'Mostrar metadatos',
  'editor.show_description': 'Mostrar descripcion',
  'editor.show_instructions': 'Mostrar instrucciones',
  'editor.show_geometry': 'Mostrar mapa de área',
  'editor.geometry_style': 'Estilo del mapa de área',
  'editor.geometry_style_shape': 'Solo contorno',
  'editor.geometry_style_map': 'Mosaicos de mapa (en línea)',
  'editor.show_provider': 'Mostrar proveedor',
  'editor.show_source_link': 'Mostrar enlace de fuente',
  'editor.reformat_text': 'Reformatear texto (eliminar saltos de linea)',
  'editor.compact': 'Disposicion compacta',
  'editor.font_size': 'Tamaño de fuente',
  'editor.font_size_small': 'Pequeño',
  'editor.font_size_default': 'Predeterminado',
  'editor.font_size_large': 'Grande',
  'editor.font_size_x_large': 'Extra grande',
  'editor.hide_expired': 'Ocultar alertas expiradas',
  'editor.hide_no_alerts': 'Ocultar tarjeta sin alertas',
  'editor.unavailable_behavior': 'Cuando el sensor de alerta falla',
  'editor.unavailable_message': 'Mostrar aviso completo',
  'editor.unavailable_compact': 'Mostrar aviso compacto',
  'editor.unavailable_hide': 'Ocultar tarjeta (no recomendado)',
  'editor.unavailable_hide_warning': 'Ocultar la tarjeta cuando un sensor no está disponible puede enmascarar una fuente de alerta averiada: un sensor no disponible no es prueba de seguridad.',
  'editor.allow_dismiss': 'Permitir descartar alertas',
  'editor.show_dismiss_undo': 'Mostrar notificación para deshacer',
  'editor.dismissed_count': 'Descartadas: {count} alertas.',
  'editor.dismissed_count_singular': 'Descartada: {count} alerta.',
  'editor.restore_all': 'Restaurar todo',
  'editor.show_preview': 'Mostrar datos de ejemplo',
  'editor.preview_hint': 'Vista previa con alertas de ejemplo',
  'editor.preview_nudge': 'Sin alertas activas — active para previsualizar el diseno.',
  'editor.entity_warning': 'La entidad seleccionada no parece contener datos de alerta meteorologica.',
  'editor.no_entities_hint': 'No se encontraron entidades de alerta meteorologica compatibles. Se debe instalar una integracion (ej. NWS Alerts).',
  'editor.no_entities_hint_link': 'Proveedores compatibles',
  'editor.no_device_alerts_hint': 'Aun no se encontraron sensores de alerta activos bajo este dispositivo. La tarjeta se rellenara automaticamente cuando CAP Alerts publique alertas.',

  // Editor section labels
  'editor.section_entity': 'Entidad y proveedor',
  'editor.section_filtering': 'Filtrado',
  'editor.section_appearance': 'Apariencia',
  'editor.section_detail_panel': 'Panel de detalles',
  'editor.section_behavior': 'Comportamiento',
  'editor.section_dismissal': 'Descarte',
  'editor.dismiss_trigger': 'Disparador',
  'editor.dismiss_trigger_button': 'Solo boton',
  'editor.dismiss_trigger_swipe': 'Solo deslizamiento',
  'editor.dismiss_trigger_both': 'Boton y deslizamiento',
  'editor.dismiss_button_style': 'Estilo del boton',
  'editor.dismiss_button_style_icon': 'Solo icono',
  'editor.dismiss_button_style_labeled': 'Icono y texto',
};

const it: TranslationMap = {
  // Card UI
  'card.no_alerts': 'Nessuna allerta attiva.',
  'card.sensor_unavailable': 'Il sensore di allerta è {state}.',
  'card.preview': 'Dati di esempio',
  'card.read_details': 'Leggi dettagli',
  'card.open_source': 'Apri fonte {provider}',
  'card.zones_count': '{count} zone',
  'card.zone_count_singular': '{count} zona',
  'card.dismiss': 'Ignora',
  'card.dismissed_toast': 'Ignorata: {event}',
  'card.dismissed_toast_undo': 'Annulla',

  // Detail labels
  'detail.issued': 'Emessa',
  'detail.onset': 'Inizio',
  'detail.expires': 'Scadenza',
  'detail.area': 'Area',
  'detail.source': 'Fonte',
  'detail.description': 'Descrizione',
  'detail.instructions': 'Istruzioni',

  // Progress bar
  'progress.start': 'Inizio',
  'progress.now': 'Ora',
  'progress.end': 'Fine',
  'progress.ongoing': 'In corso',
  'progress.expires_in_label': 'Scade tra',
  'progress.starts_in_label': 'Inizia tra',
  'progress.tbd': 'N.D.',
  'progress.na': 'N/D',
  'progress.expired_label': 'Scaduta',
  'progress.compact_active': 'per {time}',
  'progress.compact_prep': 'tra {time}',
  'progress.compact_ongoing': 'in corso',
  'progress.compact_expired': 'scaduta {time} fa',

  // Relative time
  'time.just_now': 'proprio ora',
  'time.in_less_than_1m': 'in <1m',
  'time.minutes_ago': '{m}m fa',
  'time.in_minutes': 'in {m}m',
  'time.hours_ago': '{dur} fa',
  'time.in_hours': 'in {dur}',
  'time.days_ago': '{d}g fa',
  'time.in_days': 'in {d}g',

  // Badge labels
  'badge.severity_extreme': 'Estrema',
  'badge.severity_severe': 'Grave',
  'badge.severity_moderate': 'Moderata',
  'badge.severity_minor': 'Lieve',
  'badge.severity_unknown': 'Sconosciuta',
  'badge.certainty_observed': 'Osservata',
  'badge.certainty_likely': 'Probabile',
  'badge.certainty_possible': 'Possibile',
  'badge.certainty_unlikely': 'Improbabile',
  'badge.certainty_unknown': 'Sconosciuta',

  // Editor
  'editor.entities': 'Entità',
  'editor.title': 'Titolo (opzionale)',
  'editor.provider': 'Fornitore allerte',
  'editor.provider_auto': 'Rilevamento automatico',
  'editor.provider_nws': 'NWS (Stati Uniti)',
  'editor.provider_bom': 'BoM (Australia)',
  'editor.provider_meteoalarm': 'MeteoAlarm (Europa)',
  'editor.provider_pirateweather': 'PirateWeather',
  'editor.provider_dwd': 'DWD (Germania)',
  'editor.provider_meteoswiss': 'MeteoSwiss (Svizzera)',
  'editor.provider_eccc': 'ECCC (Canada)',
  'editor.provider_cap': 'Allerte CAP (multi-regione)',
  'editor.device': 'Dispositivo CAP Alerts (opzionale)',
  'editor.device_helper': 'Aggiunge automaticamente ogni sensore di allerta attivo sotto questo dispositivo.',
  'editor.zones': 'Zone (opzionale)',
  'editor.zones_helper': 'Codici area_id BoM separati da virgola, es. NSW_FL049',
  'editor.event_codes': 'Codici evento (opzionale)',
  'editor.event_codes_helper': 'Codici evento separati da virgola, es. TOW, SVW (NWS) o 31, 95 (DWD)',
  'editor.exclude_event_codes': 'Escludi codici evento (opzionale)',
  'editor.exclude_event_codes_helper': 'Codici evento da escludere, es. SCY (NWS) o 22 (DWD)',
  'editor.sort_order': 'Ordinamento',
  'editor.sort_default': 'Predefinito',
  'editor.sort_onset': 'Ora di inizio',
  'editor.sort_severity': 'Gravità',
  'editor.color_theme': 'Tema colori',
  'editor.color_severity': 'Basato sulla gravità',
  'editor.color_nws': 'NWS ufficiale',
  'editor.color_meteoalarm': 'MeteoAlarm Livelli',
  'editor.color_eccc': 'Allerte pubbliche ECCC',
  'editor.timezone': 'Fuso orario',
  'editor.tz_server': 'Server (Home Assistant)',
  'editor.tz_browser': 'Browser (dispositivo locale)',
  'editor.min_severity': 'Gravità minima',
  'editor.severity_all': 'Tutte le gravità',
  'editor.severity_minor': 'Lieve o superiore',
  'editor.severity_moderate': 'Moderata o superiore',
  'editor.severity_severe': 'Grave o superiore',
  'editor.severity_extreme': 'Solo estrema',
  'editor.animations': 'Abilita animazioni',
  'editor.enhance_contrast': 'Migliora contrasto',
  'editor.enhance_contrast_off': 'Disattivato',
  'editor.enhance_contrast_subtle': 'Sottile (predefinito)',
  'editor.enhance_contrast_strict': 'Rigoroso (WCAG AA)',
  'editor.deduplicate': 'Deduplica allerte',
  'editor.deduplicate_headlines': 'Deduplica titoli',
  'editor.show_details': 'Mostra pannello dettagli',
  'editor.expand_details': 'Espandi sempre i dettagli',
  'editor.show_metadata': 'Mostra metadati',
  'editor.show_description': 'Mostra descrizione',
  'editor.show_instructions': 'Mostra istruzioni',
  'editor.show_geometry': 'Mostra mappa area',
  'editor.geometry_style': 'Stile mappa area',
  'editor.geometry_style_shape': 'Solo contorno',
  'editor.geometry_style_map': 'Tile mappa (online)',
  'editor.show_provider': 'Mostra fornitore',
  'editor.show_source_link': 'Mostra link alla fonte',
  'editor.reformat_text': 'Riformatta testo (rimuovi interruzioni di riga)',
  'editor.compact': 'Layout compatto',
  'editor.font_size': 'Dimensione testo',
  'editor.font_size_small': 'Piccolo',
  'editor.font_size_default': 'Predefinito',
  'editor.font_size_large': 'Grande',
  'editor.font_size_x_large': 'Molto grande',
  'editor.hide_expired': 'Nascondi allerte scadute',
  'editor.hide_no_alerts': 'Nascondi scheda senza allerte',
  'editor.unavailable_behavior': 'Quando il sensore di allerta è guasto',
  'editor.unavailable_message': 'Mostra avviso completo',
  'editor.unavailable_compact': 'Mostra avviso compatto',
  'editor.unavailable_hide': 'Nascondi scheda (sconsigliato)',
  'editor.unavailable_hide_warning': 'Nascondere la scheda quando un sensore non è disponibile può mascherare una fonte di allerta guasta: un sensore non disponibile non è prova di sicurezza.',
  'editor.allow_dismiss': 'Consenti di ignorare le allerte',
  'editor.show_dismiss_undo': 'Mostra notifica di annullamento',
  'editor.dismissed_count': 'Ignorate: {count} allerte.',
  'editor.dismissed_count_singular': 'Ignorata: {count} allerta.',
  'editor.restore_all': 'Ripristina tutto',
  'editor.show_preview': 'Mostra dati di esempio',
  'editor.preview_hint': 'Anteprima del layout con allerte di esempio',
  'editor.preview_nudge': 'Nessuna allerta attiva — attiva per visualizzare il layout.',
  'editor.entity_warning': 'L\'entità selezionata non sembra contenere dati di allerta meteo.',
  'editor.no_entities_hint': 'Nessuna entita di allerta meteo compatibile trovata. Un\'integrazione (es. NWS Alerts) deve essere installata.',
  'editor.no_entities_hint_link': 'Provider supportati',
  'editor.no_device_alerts_hint': 'Nessun sensore di allerta attivo trovato sotto questo dispositivo per ora. La scheda si popolera automaticamente quando CAP Alerts pubblichera delle allerte.',

  // Editor section labels
  'editor.section_entity': 'Entità e fornitore',
  'editor.section_filtering': 'Filtraggio',
  'editor.section_appearance': 'Aspetto',
  'editor.section_detail_panel': 'Pannello dettagli',
  'editor.section_behavior': 'Comportamento',
  'editor.section_dismissal': 'Dismissione',
  'editor.dismiss_trigger': 'Attivatore',
  'editor.dismiss_trigger_button': 'Solo pulsante',
  'editor.dismiss_trigger_swipe': 'Solo scorrimento',
  'editor.dismiss_trigger_both': 'Pulsante e scorrimento',
  'editor.dismiss_button_style': 'Stile pulsante',
  'editor.dismiss_button_style_icon': 'Solo icona',
  'editor.dismiss_button_style_labeled': 'Icona e testo',
};

const de: TranslationMap = {
  // Card UI
  'card.no_alerts': 'Keine aktiven Warnungen.',
  'card.sensor_unavailable': 'Der Warnsensor ist {state}.',
  'card.preview': 'Beispieldaten',
  'card.read_details': 'Details lesen',
  'card.open_source': '{provider}-Quelle öffnen',
  'card.zones_count': '{count} Zonen',
  'card.zone_count_singular': '{count} Zone',
  'card.dismiss': 'Ausblenden',
  'card.dismissed_toast': 'Ausgeblendet: {event}',
  'card.dismissed_toast_undo': 'Rückgängig',

  // Detail labels
  'detail.issued': 'Ausgegeben',
  'detail.onset': 'Beginn',
  'detail.expires': 'Ablauf',
  'detail.area': 'Gebiet',
  'detail.source': 'Quelle',
  'detail.description': 'Beschreibung',
  'detail.instructions': 'Hinweise',

  // Progress bar
  'progress.start': 'Start',
  'progress.now': 'Jetzt',
  'progress.end': 'Ende',
  'progress.ongoing': 'Laufend',
  'progress.expires_in_label': 'Endet in',
  'progress.starts_in_label': 'Beginnt in',
  'progress.tbd': 'Offen',
  'progress.na': 'K. A.',
  'progress.expired_label': 'Abgelaufen',
  'progress.compact_active': 'für {time}',
  'progress.compact_prep': 'in {time}',
  'progress.compact_ongoing': 'laufend',
  'progress.compact_expired': 'abgelaufen vor {time}',

  // Relative time
  'time.just_now': 'gerade eben',
  'time.in_less_than_1m': 'in <1 Min',
  'time.minutes_ago': 'vor {m} Min',
  'time.in_minutes': 'in {m} Min',
  'time.hours_ago': 'vor {dur}',
  'time.in_hours': 'in {dur}',
  'time.days_ago': 'vor {d} T',
  'time.in_days': 'in {d} T',

  // Badge labels
  'badge.severity_extreme': 'Extrem',
  'badge.severity_severe': 'Schwer',
  'badge.severity_moderate': 'Mäßig',
  'badge.severity_minor': 'Gering',
  'badge.severity_unknown': 'Unbekannt',
  'badge.certainty_observed': 'Beobachtet',
  'badge.certainty_likely': 'Wahrscheinlich',
  'badge.certainty_possible': 'Möglich',
  'badge.certainty_unlikely': 'Unwahrscheinlich',
  'badge.certainty_unknown': 'Unbekannt',

  // Editor
  'editor.entities': 'Entitäten',
  'editor.title': 'Titel (optional)',
  'editor.provider': 'Warnanbieter',
  'editor.provider_auto': 'Automatisch erkennen',
  'editor.provider_nws': 'NWS (USA)',
  'editor.provider_bom': 'BoM (Australien)',
  'editor.provider_meteoalarm': 'MeteoAlarm (Europa)',
  'editor.provider_pirateweather': 'PirateWeather',
  'editor.provider_dwd': 'DWD (Deutschland)',
  'editor.provider_meteoswiss': 'MeteoSwiss (Schweiz)',
  'editor.provider_eccc': 'ECCC (Kanada)',
  'editor.provider_cap': 'CAP-Warnungen (multi-regional)',
  'editor.device': 'CAP-Alerts-Gerät (optional)',
  'editor.device_helper': 'Bezieht automatisch jeden aktiven Warnsensor unter diesem Gerät ein.',
  'editor.zones': 'Zonen (optional)',
  'editor.zones_helper': 'Kommagetrennte BoM area_id-Codes, z. B. NSW_FL049',
  'editor.event_codes': 'Ereigniscodes (optional)',
  'editor.event_codes_helper': 'Kommagetrennte Ereigniscodes, z. B. TOW, SVW (NWS) oder 31, 95 (DWD)',
  'editor.exclude_event_codes': 'Ereigniscodes ausschließen (optional)',
  'editor.exclude_event_codes_helper': 'Ereigniscodes zum Ausschließen, z. B. SCY (NWS) oder 22 (DWD)',
  'editor.sort_order': 'Sortierung',
  'editor.sort_default': 'Standard',
  'editor.sort_onset': 'Beginnzeit',
  'editor.sort_severity': 'Schweregrad',
  'editor.color_theme': 'Farbschema',
  'editor.color_severity': 'Nach Schweregrad',
  'editor.color_nws': 'NWS offiziell',
  'editor.color_meteoalarm': 'MeteoAlarm Warnstufen',
  'editor.color_eccc': 'ECCC öffentliche Warnungen',
  'editor.timezone': 'Zeitzone',
  'editor.tz_server': 'Server (Home Assistant)',
  'editor.tz_browser': 'Browser (lokales Gerät)',
  'editor.min_severity': 'Mindestschweregrad',
  'editor.severity_all': 'Alle Schweregrade',
  'editor.severity_minor': 'Gering oder höher',
  'editor.severity_moderate': 'Mäßig oder höher',
  'editor.severity_severe': 'Schwer oder höher',
  'editor.severity_extreme': 'Nur extrem',
  'editor.animations': 'Animationen aktivieren',
  'editor.enhance_contrast': 'Kontrast erhöhen',
  'editor.enhance_contrast_off': 'Aus',
  'editor.enhance_contrast_subtle': 'Dezent (Standard)',
  'editor.enhance_contrast_strict': 'Streng (WCAG AA)',
  'editor.deduplicate': 'Warnungen deduplizieren',
  'editor.deduplicate_headlines': 'Überschriften deduplizieren',
  'editor.show_details': 'Detailbereich anzeigen',
  'editor.expand_details': 'Details immer anzeigen',
  'editor.show_metadata': 'Metadaten anzeigen',
  'editor.show_description': 'Beschreibung anzeigen',
  'editor.show_instructions': 'Hinweise anzeigen',
  'editor.show_geometry': 'Gebietskarte anzeigen',
  'editor.geometry_style': 'Gebietskartenstil',
  'editor.geometry_style_shape': 'Nur Umriss',
  'editor.geometry_style_map': 'Kartenkacheln (online)',
  'editor.show_provider': 'Anbieter anzeigen',
  'editor.show_source_link': 'Quelllink anzeigen',
  'editor.reformat_text': 'Text umformatieren (harte Zeilenumbrüche entfernen)',
  'editor.compact': 'Kompaktes Layout',
  'editor.font_size': 'Schriftgröße',
  'editor.font_size_small': 'Klein',
  'editor.font_size_default': 'Standard',
  'editor.font_size_large': 'Groß',
  'editor.font_size_x_large': 'Sehr groß',
  'editor.hide_expired': 'Abgelaufene Warnungen ausblenden',
  'editor.hide_no_alerts': 'Karte ohne aktive Warnungen ausblenden',
  'editor.unavailable_behavior': 'Wenn der Warnsensor gestört ist',
  'editor.unavailable_message': 'Vollständigen Hinweis anzeigen',
  'editor.unavailable_compact': 'Kompakten Hinweis anzeigen',
  'editor.unavailable_hide': 'Karte ausblenden (nicht empfohlen)',
  'editor.unavailable_hide_warning': 'Das Ausblenden der Karte bei einem nicht verfügbaren Sensor kann eine gestörte Warnquelle verschleiern — ein nicht verfügbarer Sensor ist kein Beweis für Sicherheit.',
  'editor.allow_dismiss': 'Warnungen ausblendbar machen',
  'editor.show_dismiss_undo': 'Rückgängig-Benachrichtigung anzeigen',
  'editor.dismissed_count': 'Ausgeblendet: {count} Warnungen.',
  'editor.dismissed_count_singular': 'Ausgeblendet: {count} Warnung.',
  'editor.restore_all': 'Alle wiederherstellen',
  'editor.show_preview': 'Beispieldaten anzeigen',
  'editor.preview_hint': 'Kartenlayout mit Beispielwarnungen anzeigen',
  'editor.preview_nudge': 'Keine aktiven Warnungen — aktivieren, um das Kartenlayout zu sehen.',
  'editor.entity_warning': 'Die ausgewählte Entität scheint keine Wetterwarnungsdaten zu enthalten.',
  'editor.no_entities_hint': 'Keine kompatiblen Wetterwarnungs-Entitaten gefunden. Eine Integration (z.B. NWS Alerts) muss installiert sein.',
  'editor.no_entities_hint_link': 'Unterstutzte Anbieter',
  'editor.no_device_alerts_hint': 'Noch keine aktiven Warnsensoren unter diesem Gerat gefunden. Die Karte fullt sich automatisch, sobald CAP Alerts Warnungen veroffentlicht.',

  // Editor section labels
  'editor.section_entity': 'Entität und Anbieter',
  'editor.section_filtering': 'Filterung',
  'editor.section_appearance': 'Darstellung',
  'editor.section_detail_panel': 'Detailbereich',
  'editor.section_behavior': 'Verhalten',
  'editor.section_dismissal': 'Ausblenden',
  'editor.dismiss_trigger': 'Auslöser',
  'editor.dismiss_trigger_button': 'Nur Schaltfläche',
  'editor.dismiss_trigger_swipe': 'Nur wischen',
  'editor.dismiss_trigger_both': 'Schaltfläche und wischen',
  'editor.dismiss_button_style': 'Schaltflächenstil',
  'editor.dismiss_button_style_icon': 'Nur Symbol',
  'editor.dismiss_button_style_labeled': 'Symbol und Text',
};

const zh: TranslationMap = {
  // Card UI
  'card.no_alerts': '无活动警报。',
  'card.sensor_unavailable': '警报传感器状态为 {state}。',
  'card.preview': '示例数据',
  'card.read_details': '查看详情',
  'card.open_source': '打开 {provider} 来源',
  'card.zones_count': '{count} 个区域',
  'card.zone_count_singular': '{count} 个区域',
  'card.dismiss': '关闭',
  'card.dismissed_toast': '已关闭：{event}',
  'card.dismissed_toast_undo': '撤销',

  // Detail labels
  'detail.issued': '发布',
  'detail.onset': '开始',
  'detail.expires': '过期',
  'detail.area': '区域',
  'detail.source': '来源',
  'detail.description': '描述',
  'detail.instructions': '说明',

  // Progress bar
  'progress.start': '开始',
  'progress.now': '现在',
  'progress.end': '结束',
  'progress.ongoing': '进行中',
  'progress.expires_in_label': '将在',
  'progress.starts_in_label': '将在',
  'progress.tbd': '待定',
  'progress.na': '不可用',
  'progress.expired_label': '已过期',
  'progress.compact_active': '持续 {time}',
  'progress.compact_prep': '{time} 后',
  'progress.compact_ongoing': '进行中',
  'progress.compact_expired': '{time} 前已过期',

  // Relative time
  'time.just_now': '刚刚',
  'time.in_less_than_1m': '<1分钟内',
  'time.minutes_ago': '{m}分钟前',
  'time.in_minutes': '{m}分钟后',
  'time.hours_ago': '{dur}前',
  'time.in_hours': '{dur}后',
  'time.days_ago': '{d}天前',
  'time.in_days': '{d}天后',

  // Badge labels
  'badge.severity_extreme': '极端',
  'badge.severity_severe': '严重',
  'badge.severity_moderate': '中等',
  'badge.severity_minor': '轻微',
  'badge.severity_unknown': '未知',
  'badge.certainty_observed': '已观测',
  'badge.certainty_likely': '很可能',
  'badge.certainty_possible': '可能',
  'badge.certainty_unlikely': '不太可能',
  'badge.certainty_unknown': '未知',

  // Editor
  'editor.entities': '实体',
  'editor.title': '标题（可选）',
  'editor.provider': '警报提供商',
  'editor.provider_auto': '自动检测',
  'editor.provider_nws': 'NWS（美国）',
  'editor.provider_bom': 'BoM（澳大利亚）',
  'editor.provider_meteoalarm': 'MeteoAlarm（欧洲）',
  'editor.provider_pirateweather': 'PirateWeather',
  'editor.provider_dwd': 'DWD（德国）',
  'editor.provider_meteoswiss': 'MeteoSwiss（瑞士）',
  'editor.provider_eccc': 'ECCC（加拿大）',
  'editor.provider_cap': 'CAP警报（多地区）',
  'editor.device': 'CAP警报设备（可选）',
  'editor.device_helper': '自动获取此设备下的所有活动警报传感器。',
  'editor.zones': '区域（可选）',
  'editor.zones_helper': '逗号分隔的BoM area_id代码，例如NSW_FL049',
  'editor.event_codes': '事件代码（可选）',
  'editor.event_codes_helper': '逗号分隔的事件代码，例如TOW、SVW（NWS）或31、95（DWD）',
  'editor.exclude_event_codes': '排除事件代码（可选）',
  'editor.exclude_event_codes_helper': '要排除的事件代码，例如SCY（NWS）或22（DWD）',
  'editor.sort_order': '排序顺序',
  'editor.sort_default': '默认',
  'editor.sort_onset': '开始时间',
  'editor.sort_severity': '严重程度',
  'editor.color_theme': '颜色主题',
  'editor.color_severity': '基于严重程度',
  'editor.color_nws': 'NWS官方',
  'editor.color_meteoalarm': 'MeteoAlarm意识级别',
  'editor.color_eccc': 'ECCC公共警报',
  'editor.timezone': '时区',
  'editor.tz_server': '服务器（Home Assistant）',
  'editor.tz_browser': '浏览器（本地设备）',
  'editor.min_severity': '最低严重程度',
  'editor.severity_all': '所有严重程度',
  'editor.severity_minor': '轻微或更高',
  'editor.severity_moderate': '中等或更高',
  'editor.severity_severe': '严重或更高',
  'editor.severity_extreme': '仅极端',
  'editor.animations': '启用动画',
  'editor.enhance_contrast': '增强对比度',
  'editor.enhance_contrast_off': '关闭',
  'editor.enhance_contrast_subtle': '轻微（默认）',
  'editor.enhance_contrast_strict': '严格（WCAG AA）',
  'editor.deduplicate': '去重警报',
  'editor.deduplicate_headlines': '去重标题',
  'editor.show_details': '显示详情面板',
  'editor.expand_details': '始终展开详情',
  'editor.show_metadata': '显示元数据',
  'editor.show_description': '显示描述',
  'editor.show_instructions': '显示说明',
  'editor.show_geometry': '显示区域地图',
  'editor.geometry_style': '区域地图样式',
  'editor.geometry_style_shape': '仅轮廓',
  'editor.geometry_style_map': '地图瓦片（在线）',
  'editor.show_provider': '显示提供商标签',
  'editor.show_source_link': '显示来源链接',
  'editor.reformat_text': '重新格式化警报文本（删除硬换行）',
  'editor.compact': '紧凑布局',
  'editor.font_size': '字体大小',
  'editor.font_size_small': '小',
  'editor.font_size_default': '默认',
  'editor.font_size_large': '大',
  'editor.font_size_x_large': '超大',
  'editor.hide_expired': '隐藏过期警报',
  'editor.hide_no_alerts': '无活动警报时隐藏卡片',
  'editor.unavailable_behavior': '当警报传感器损坏时',
  'editor.unavailable_message': '显示完整通知',
  'editor.unavailable_compact': '显示紧凑通知',
  'editor.unavailable_hide': '隐藏卡片（不推荐）',
  'editor.unavailable_hide_warning': '当传感器不可用时隐藏卡片可能会掩盖损坏的警报源 — 不可用的传感器不能证明安全。',
  'editor.allow_dismiss': '允许关闭警报',
  'editor.show_dismiss_undo': '关闭时显示撤销通知',
  'editor.dismissed_count': '已关闭：{count} 个警报。',
  'editor.dismissed_count_singular': '已关闭：{count} 个警报。',
  'editor.restore_all': '全部恢复',
  'editor.show_preview': '显示示例数据',
  'editor.preview_hint': '使用示例警报预览卡片布局',
  'editor.preview_nudge': '无活动警报 — 启用以预览卡片布局。',
  'editor.entity_warning': '所选实体似乎不包含天气警报数据。',
  'editor.no_entities_hint': '未找到支持的天气警报实体。必须先安装提供商集成（例如NWS警报）。',
  'editor.no_entities_hint_link': '支持的提供商',
  'editor.no_device_alerts_hint': '此设备下尚未找到活动警报传感器。当CAP警报发布警报时，卡片将自动填充。',

  // Editor section labels
  'editor.section_entity': '实体和提供商',
  'editor.section_filtering': '过滤',
  'editor.section_appearance': '外观',
  'editor.section_detail_panel': '详情面板',
  'editor.section_behavior': '行为',
  'editor.section_dismissal': '关闭',
  'editor.dismiss_trigger': '关闭触发器',
  'editor.dismiss_trigger_button': '仅按钮',
  'editor.dismiss_trigger_swipe': '仅滑动',
  'editor.dismiss_trigger_both': '按钮和滑动',
  'editor.dismiss_button_style': '按钮样式',
  'editor.dismiss_button_style_icon': '仅图标',
  'editor.dismiss_button_style_labeled': '图标和文字',
};

const translations: Record<string, TranslationMap> = { en, fr, es, it, de, zh };

export function t(key: string, lang: string, params?: Record<string, string | number>): string {
  const baseLang = lang.split('-')[0].toLowerCase();
  const map = translations[baseLang] || translations.en;
  let value = map[key] ?? translations.en[key] ?? key;

  if (params) {
    for (const [k, v] of Object.entries(params)) {
      // split/join replaces every occurrence — String.replace(str, …) only
      // replaces the first, which would leave repeated placeholders intact.
      value = value.split(`{${k}}`).join(String(v));
    }
  }

  return value;
}
